trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: DevOps/opsguild.automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: AVEVA/AVEVA-Samples
      endpoint: AVEVA

variables:
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.eds_azure.ini
  - name: InstallFile
    value: loc.ini
  - name: InstallFileLibrary
    value: product-readiness.eds_install_loc.ini
  - name: analysisProject
    value: EDS_Deployment_Install

parameters:
  - name: pool
    default: DevOps Managed Containers Build
  - name: containerDemands
    type: object
    default: ['Agent.OS -equals Linux']

jobs:
  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)

      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(InstallFile)
          fileLibrary: $(InstallFileLibrary)

      - bash: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
        displayName: 'Install Azure CLI'

      - bash: |
          chmod +x test.sh
          chmod +x remote.sh
          chmod +x reset.sh
          chmod +x reset-device.sh
          ./test.sh
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      skipPolaris: true
